# Generated by Django 4.0.7 on 2023-05-24 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0054_remove_entityuploadchildlv1_poi_distance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approve', models.BooleanField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('logs', models.TextField(blank=True, null=True)),
                ('upload_ids', models.JSONField(blank=True, default=[], help_text='List of entity uploads', null=True)),
                ('processed_ids', models.JSONField(blank=True, default=[], help_text='List of entity uploads that has been processed', null=True)),
                ('task_id', models.CharField(blank=True, default='', help_text='running task id', max_length=256)),
                ('progress', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Error', 'Error'), ('Done', 'Done')], default='', max_length=100)),
                ('review_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
